### model
model_name_or_path: Qwen/Qwen3-8B
model_revision: main
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: env_factory_mini_train
eval_dataset: env_factory_mini_validation
dataset_dir: __RUN_DATASET_DIR__
template: qwen3
mask_history: true
cutoff_len: 8192
overwrite_cache: false
preprocessing_num_workers: 3
dataloader_num_workers: 2

### output
output_dir: __RUN_OUTPUT_DIR__
logging_dir: __RUN_TENSORBOARD_DIR__
logging_steps: 10
save_steps: 10
save_strategy: steps
save_total_limit: 3
plot_loss: true
overwrite_output_dir: false
save_only_model: false
report_to: tensorboard

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-6
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000
seed: 42
data_seed: 42
resume_from_checkpoint: null

### eval
do_eval: true
per_device_eval_batch_size: 1
eval_strategy: epoch
